api:
  image: docker.dennajort.fr/nourriturebjtu_api
  environment:
    UPLOADS_PATH: "/uploads"
    NODE_ENV: "production"
  links:
    - mongodb
  volumes_from:
    - apiupload
  ports:
    - "80:3000"

apiupload:
  image: busybox
  volumes:
    - /uploads
  command: true

mongodb:
  image: mongo:2.6.7
  command: mongod --smallfiles
  volumes_from:
    - mongodbdata

mongodbdata:
  image: busybox
  volumes:
    - /data/db
  command: true
